image:
  - Visual Studio 2017

environment:
  global:
    NAME: openal
    CONFIG: Release
    ASDF_SYSTEM: bodge-openal
  matrix:
  - platform: x64
    MSYS_PATH: C:\msys64\mingw64\bin\;C:\msys64\usr\bin\
    TARGET_ARCH: x86_64
    GENERATOR: "Visual Studio 15 2017 Win64"
  - platform: x86
    MSYS_PATH: C:\msys64\mingw32\bin\;C:\msys64\usr\bin\
    TARGET_ARCH: i686
    GENERATOR: "Visual Studio 15 2017"

skip_non_tags: true

branches:
  only:
    - master
    - "/^v\\d+(\\.\\d+)+$/"


install:
  - git submodule update --init --recursive --depth=2

build_script:
  - cd src/lib/openal/build
  - >-
    cmake -G"%GENERATOR%" -DCMAKE_BUILD_TYPE=Release
    -DALSOFT_BUILD_ROUTER=OFF -DALSOFT_REQUIRE_WINMM=ON -DALSOFT_REQUIRE_DSOUND=ON
    -DALSOFT_REQUIRE_WASAPI=ON -DALSOFT_EMBED_HRTF_DATA=YES
    -DALSOFT_UTILS=OFF -DALSOFT_NO_CONFIG_UTIL=OFF -DALSOFT_EXAMPLES=OFF
    -DALSOFT_TESTS=OFF -DALSOFT_CONFIG=OFF -DALSOFT_INSTALL=OFF
    -DALSOFT_CPUEXT_SSE3=OFF -DALSOFT_CPUEXT_SSE4_1=OFF ..
  - cmake --build . --config Release --clean-first
  - set TARGET_ARTIFACT=lib%NAME%.dll.bodged-%TARGET_ARCH%-windows-%APPVEYOR_REPO_TAG_NAME%
  - set TARGET_SPEC=%TARGET_ARTIFACT%-spec.zip
  - set PATH=%MSYS_PATH%;%PATH%
  - set APPVEYOR_BUILD_DIR=$(cygpath -u '%APPVEYOR_BUILD_FOLDER%')
  - curl -L http://bodge.borodust.org/files/install.sh | sh
  - pacman --needed --noconfirm -S zip unzip base-devel
  - sh -c "~/.bodge/bin/lisp regen-local-spec-and-zip --arch %TARGET_ARCH% \"$(cygpath -u '%APPVEYOR_BUILD_FOLDER%')\" %ASDF_SYSTEM% \"$(cygpath -u '%APPVEYOR_BUILD_FOLDER%\%TARGET_SPEC%')\""
  - mv %APPVEYOR_BUILD_FOLDER%\src\lib\openal\build\Release\OpenAL32.dll %APPVEYOR_BUILD_FOLDER%\%TARGET_ARTIFACT%

artifacts:
  - path: $(TARGET_ARTIFACT)
    name: target_artifact
  - path: $(TARGET_SPEC)
    name: target_spec

deploy:
  provider: GitHub
  release: $(APPVEYOR_REPO_TAG_NAME)
  tag: $(APPVEYOR_REPO_TAG_NAME)
  description: $(APPVEYOR_REPO_COMMIT_MESSAGE)
  auth_token:
    secure: Z5XWjDOBlCrmfz3SQAjnLKtdgI5B2b/owJhRPNWYGrI+qwVNbBc4cZiroBZReWP7
  artifact: target_artifact, target_spec
  force_update: true
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true
