image:
  - Visual Studio 2017

environment:
  global:
    NAME: openal
    CONFIG: Release
  matrix:
  - platform: x64
    ARCH: x86_64
    GENERATOR: "Visual Studio 15 2017 Win64"
  - platform: x86
    ARCH: i686
    GENERATOR: "Visual Studio 15 2017"

skip_non_tags: true

branches:
  only:
    - master
    - "/^v\\d+(\\.\\d+)+$/"


install:
  - git submodule update --init --recursive

build_script:
  - set TARGET_ARTIFACT=lib%NAME%.dll.bodged-%ARCH%-windows-%APPVEYOR_REPO_TAG_NAME%
  - cd lib\openal\build
  - >
    cmake -G"%GENERATOR%"
    -DALSOFT_REQUIRE_WINMM=ON
    -DALSOFT_REQUIRE_DSOUND=ON
    -DALSOFT_REQUIRE_MMDEVAPI=ON
    -DALSOFT_UTILS=OFF
    -DALSOFT_NO_CONFIG_UTIL=OFF
    -DALSOFT_EXAMPLES=OFF
    -DALSOFT_TESTS=OFF
    -DALSOFT_CONFIG=OFF
    -DALSOFT_INSTALL=OFF
    -DALSOFT_CPUEXT_SSE3=OFF
    -DALSOFT_CPUEXT_SSE4_1=OFF
    -DALSOFT_EMBED_HRTF_DATA=YES ..
  - cmake --build . --config Release --clean-first
  - mv %APPVEYOR_BUILD_FOLDER%\lib\openal\build\Release\OpenAL32.dll %APPVEYOR_BUILD_FOLDER%\%TARGET_ARTIFACT%

artifacts:
  - path: $(TARGET_ARTIFACT)
    name: target_artifact

deploy:
  provider: GitHub
  release: $(APPVEYOR_REPO_TAG_NAME)
  tag: $(APPVEYOR_REPO_TAG_NAME)
  description: $(APPVEYOR_REPO_COMMIT_MESSAGE)
  auth_token:
    secure: Z5XWjDOBlCrmfz3SQAjnLKtdgI5B2b/owJhRPNWYGrI+qwVNbBc4cZiroBZReWP7
  artifact: target_artifact
  force_update: true
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true
